[package]
name = "protosol"
version = "2.0.0"
edition = "2021"
license = "Apache-2.0"
description = "Protobuf definitions for the SVM fuzzing project."
repository = "https://github.com/firedancer-io/protosol"
authors = ["Firedancer Team"]
keywords = ["solana", "protobuf", "sealevel", "fuzzing"]
categories = ["encoding"]
readme = "README.md"
links = "protosol"

[build-dependencies]
prost-build = "0.11.9"

[dependencies]
prost = "0.11.9"
